/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.connect_loaisp;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84867
 */
public class frm_qlloaisp extends javax.swing.JFrame {

    /**
     * Creates new form frm_qlloaisp
     */
    public frm_qlloaisp() {
        initComponents();
        loadData();
    }
    @SuppressWarnings("unchecked")
public void loadData()
{
     DefaultTableModel model = (DefaultTableModel) tb_loaisp.getModel();
          model.setRowCount(100);
         model.setColumnCount(2);
         tb_loaisp.removeAll();
        
   
 try {
 connect_loaisp pt = new connect_loaisp();
 java.sql.ResultSet rs = null;
  rs = pt.GetData("loaisp");
 int i=0;
 while (rs.next()){
 tb_loaisp.setValueAt(rs.getString("maloai"), i, 0);
 tb_loaisp.setValueAt(rs.getString("tenloai"), i, 1);

 i++;
 }
     pt.Close();
 } catch (ClassNotFoundException ex) {
 Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, 
ex);
 } catch (SQLException ex) {
Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, 
ex);
 }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmaloai = new javax.swing.JTextField();
        txt_tenloai = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_loaisp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ma Loai :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ten Loai :");

        btn_them.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_them.setText("Them");
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_sua.setText("Sua");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_xoa.setText("Xoa");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });

        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_thoat.setText("Thoat");
        btn_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thoatMouseClicked(evt);
            }
        });
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        tb_loaisp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tb_loaisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ma loai", "Ten loai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_loaisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_loaispMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_loaisp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmaloai, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txt_tenloai))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them)
                    .addComponent(btn_xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sua)
                        .addComponent(btn_thoat)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        // TODO add your handling code here:
        int row = tb_loaisp.getSelectedRow();
        int s = tb_loaisp.getSelectedColumn();
        int i = 0;
        if (txtmaloai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập  mã   !");
        } else if (txt_tenloai.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên sản phẩm !");
        } else {
            try {
                // TODO add your handling code here:
                connect_loaisp pt = new connect_loaisp();
                java.sql.ResultSet rs = null;
                rs = pt.GetData("loaisp");
                boolean ok = false;
                while (rs.next()) {
                    if (txtmaloai.getText().equals(rs.getString("maloai"))) {
                        ok = true;
                    }
                }
                if (ok) {
                    JOptionPane.showMessageDialog(null, "Mã tài khoản đã có");
                } else {
                    pt.Insert("loaisp",txtmaloai.getText(), txt_tenloai.getText());
                    btn_them.doClick();
                    JOptionPane.showMessageDialog(null, "Bạn đã thêm thành công ");
                    loadData();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add )your handling code here:
            connect_loaisp pt = new connect_loaisp();
            pt.Delete("loaisp",txtmaloai.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) tb_loaisp.getModel();
        model.setRowCount(0);
        JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công ");
        loadData();
        
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void tb_loaispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_loaispMouseClicked
        // TODO add your handling code here:
        int row =tb_loaisp.getSelectedRow();
        String id=tb_loaisp.getValueAt(row,0).toString();
        String tensp=tb_loaisp.getValueAt(row,1).toString();
           
            txtmaloai.setText(id);
            txt_tenloai.setText(tensp);
    }//GEN-LAST:event_tb_loaispMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            connect_loaisp pt = new connect_loaisp();
            pt.Update("loaisp",txtmaloai.getText(),txt_tenloai.getText());
            btn_sua.doClick();
            JOptionPane.showMessageDialog(null, "Bạn đã sửa thành công ");
            loadData();
        } catch (ClassNotFoundException ex) {

            Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null,
                    ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null,
                    ex);
         }
    }//GEN-LAST:event_btn_suaMouseClicked

    private void btn_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thoatMouseClicked
        // TODO add your handling code here:
            frm_Admin a = new frm_Admin();
             a.setVisible(true);
                a.setLocationRelativeTo(null);
          this.setVisible(false); 
    }//GEN-LAST:event_btn_thoatMouseClicked

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_qlloaisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_qlloaisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_qlloaisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_qlloaisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_qlloaisp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_loaisp;
    private javax.swing.JTextField txt_tenloai;
    private javax.swing.JTextField txtmaloai;
    // End of variables declaration//GEN-END:variables

    private static class FrameConnection {

        public FrameConnection() {
        }
    }
}
