/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.connect_loaisp;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84867
 */
public class frm_timkiemsp extends javax.swing.JFrame {

    /**
     * Creates new form frm_timkiemsp
     */
    public frm_timkiemsp() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdb_theoten = new javax.swing.JRadioButton();
        rdb_theogia = new javax.swing.JRadioButton();
        txt_ten = new javax.swing.JTextField();
        txt_gia1 = new javax.swing.JTextField();
        txtgia2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_tim = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_timsp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Tên sản phẩm :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Giá từ :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("TÌM KIẾM SẢN PHẨM");

        rdb_theoten.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rdb_theoten.setText("Tìm theo tên");
        rdb_theoten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdb_theotenMouseClicked(evt);
            }
        });

        rdb_theogia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rdb_theogia.setText("Tìm theo giá");

        txtgia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgia2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("dến");

        btn_tim.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_tim.setText("Tìm Kiếm");
        btn_tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timMouseClicked(evt);
            }
        });

        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thoatMouseClicked(evt);
            }
        });
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        tb_timsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Loại sản phẩm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_timsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(75, 75, 75)
                                        .addComponent(txt_gia1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtgia2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(28, 28, 28)
                                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdb_theoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdb_theogia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_tim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_thoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdb_theogia)
                        .addComponent(btn_thoat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rdb_theoten)
                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tim))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txt_gia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(txtgia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgia2ActionPerformed

    private void rdb_theotenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdb_theotenMouseClicked
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_rdb_theotenMouseClicked

    private void btn_timMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) tb_timsp.getModel();
           model.setRowCount(0);
        tb_timsp.removeAll();
         model.setRowCount(100);
         model.setColumnCount(4);
           if(rdb_theoten.isSelected()== true)
        {
            
            String tenSP = txt_ten.getText().trim();
            if (tenSP.length() == 0) {
               loadData();
        }else{
  try {
   String timkiem= txt_ten.getText();
 connect_loaisp pt = new connect_loaisp();
 java.sql.ResultSet rs = null;
     rs = pt.Timkiemtheoten(timkiem.trim());
     int i=0;
     while (rs.next()){
         tb_timsp.setValueAt(rs.getString("masp"), i, 0);
         tb_timsp.setValueAt(rs.getString("tensp"), i, 1);
         tb_timsp.setValueAt(rs.getString("dongia"), i, 2);
         tb_timsp.setValueAt(rs.getString("maloai"), i, 3);
         i++;
     }
 pt.Close();
 } catch (ClassNotFoundException ex) {
 Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, 
ex);
 } catch (SQLException ex) {
Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null, 
ex);
 }
  }
        }
           if (rdb_theogia.isSelected() == true) {

            String gia1 = txt_gia1.getText().trim();
             String  gia2= txtgia2.getText().trim();
            if (gia1.length() == 0 || gia2.length() ==0) {
                loadData();
            } else {
                try {
                    String timkiem1 = txt_gia1.getText();
                    String timkiem2 = txtgia2.getText();
                    connect_loaisp pt = new connect_loaisp();
                    java.sql.ResultSet rs = null;
                    rs = pt.Timkiemtheogia(timkiem1.trim(),timkiem2.trim());
                    int i = 0;
                    while (rs.next()) {
                        tb_timsp.setValueAt(rs.getString("masp"), i, 0);
                        tb_timsp.setValueAt(rs.getString("tensp"), i, 1);
                        tb_timsp.setValueAt(rs.getString("dongia"), i, 2);
                        tb_timsp.setValueAt(rs.getString("maloai"), i, 3);
                        i++;
                    }
                    pt.Close();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null,
                            ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameConnection.class.getName()).log(Level.SEVERE, null,
                            ex);
                }
            }
        }
    }//GEN-LAST:event_btn_timMouseClicked

    private void btn_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thoatMouseClicked
        // TODO add your handling code here:
                    frm_Admin a = new frm_Admin();
             a.setVisible(true);
                a.setLocationRelativeTo(null);
          this.setVisible(false); 
    }//GEN-LAST:event_btn_thoatMouseClicked

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_thoatActionPerformed
public void loadData()
{
     DefaultTableModel model = (DefaultTableModel) tb_timsp.getModel();
          model.setRowCount(100);
         model.setColumnCount(4);
         tb_timsp.removeAll();
        
   
 try {
 connect_loaisp pt = new connect_loaisp();
 java.sql.ResultSet rs = null;
  rs = pt.GetData("sanpham");
 int i=0;

 while (rs.next()){
 tb_timsp.setValueAt(rs.getString("masp"), i, 0);
 tb_timsp.setValueAt(rs.getString("tensp"), i, 1);
 tb_timsp.setValueAt(rs.getString("dongia"), i, 2);
 tb_timsp.setValueAt(rs.getString("maloai"), i, 3);
 i++;
 }
 pt.Close();
 } catch (ClassNotFoundException ex) {
 Logger.getLogger(frm_timkiemsp.FrameConnection.class.getName()).log(Level.SEVERE, null, 
ex);
 } catch (SQLException ex) {
Logger.getLogger(frm_timkiemsp.FrameConnection.class.getName()).log(Level.SEVERE, null, 
ex);
 }
 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_timkiemsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_timkiemsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_timkiemsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_timkiemsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_timkiemsp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_theogia;
    private javax.swing.JRadioButton rdb_theoten;
    private javax.swing.JTable tb_timsp;
    private javax.swing.JTextField txt_gia1;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txtgia2;
    // End of variables declaration//GEN-END:variables

    private static class FrameConnection {

        public FrameConnection() {
        }
    }
}
